### ISSUE TITLE
Vector Magic

### ISSUE THREAD

**Issue by techjp** [fromtheexchange/image2svg-awesome#5]
"Vector Magic is the gold standard"...

I must respectfully disagree. It hasn't been updated for well over a decade. Almost 15 years! I tested it out on their website and was extremely disappointed by the results. potrace did a far better job just using its default settings! Vector Magic may have been good 10-12 years ago but in today's world it's very overpriced and wildly underperforms.

**Comment by fromtheexchange** [comment]
I agree that Vector Magic hasn’t been updated in forever and is definitely overpriced.  However, it is cross-platform, supports batch processing and, in my experience, has superior results compared to many other apps.  I mainly echoed the sentiment I found across other forums.

While I love Potrace, it is mainly limited to a single color and is slow for large images.  Vtracer is also neat, but I’ve had trouble with it at low resolutions.  

I’m going to close this issue—but @techjp if you have suggestions for who should be recommended there, feel free to drop a link and sample images to compare.  If there’s a better and cheaper option, I’d rather recommend that option instead.  Always looking to improve the list!
